name: Deploy

on:
  push:

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest

    steps:
      -
        name: VPS - pull image and run app containters
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          ORIGIN: 192.168.1.37
          SSHKEY: ${{ secrets.KEY }}
          NAME: production
          PORT: 22
          USER: ferdibulus
      - run: ssh production "sudo docker pull ferdibulus/stockappwebservice:latest"
            
        
