name: Deploy

on:
  push:

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest

    steps:
     -
        name: VPS - pull image and run app containters
        uses: appleboy/ssh-action@v1.0.0
        with:
            proxy_host: 192.168.1.37
            proxy_username: ferdibulus
            proxy_key: ${{ secrets.KEY }}
            proxy_port: 22
            script: |
              echo "I am Ferdi"
            
        
