name: Deploy

on:
  push:

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest

    steps:
     -
        name: VPS - pull image and run app containters
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: 192.168.1.38
            username: ferdibulus
            password: Melez.Prens152
            port: 22
            proxy_host: 192.168.1.38
            proxy_username: ferdibulus
            proxy_password: Melez.Prens152
            proxy_port: 22
            script: |
              echo "I am Ferdi"
            
        
