name: Deploy

on:
  push:

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest

    steps:
      -
        name: VPS - pull image and run app containters
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          key: ${{ secrets.KEY }}
      - run: "sudo ifconfig"
            
        
