name: Release - Test, Build & Redeploy1

on:
  push:

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.0
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      -
        name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: ferdibulus
          password: dckr_pat_fUa49qOK2W0QiD2tJCDWAvZeYu4
      -
        name: Push the image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags : ferdibulus/stockappwebservice, ferdibulus/stockappwebservice:latest
      -
        name: VPS - pull image and run app containters
        uses: appleboy/ssh-action@master
        with:
          host: 92.205.30.150
          username: ferdibulus
          password: Melez.Prens152@
          port: 22
          script: |
            sudo docker pull ferdibulus/stockappwebservice:latest
            sudo docker run -d -p 8181:8181 --name stockappwebservice  --network sqlcon ferdibulus/stockappwebservice
