name: Release - Test, Build & Redeploy

on:
  push:

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Pull image to use as a cache
        run: docker pull ghcr.io/ferdibulus/stockappwebservice:latest || exit 0
      -
        name: Build Docker image
        run: docker build . --cache-from ghcr.io/ferdibulus/stockappwebservice:latest --tag ghcr.io/ferdibulus/stockappwebservice:latest
      -
        name: Push the image to GitHub Container Registry
        run: docker push ghcr.io/ferdibulus/stockappwebservice:latest
      -
        name: VPS - pull image and run app containters
        uses: appleboy/ssh-action@master
        with:
          host: 92.205.30.150
          username: ferdibulus
          password: Melez.Prens152@
          script: |
            docker-compose pull web
            docker-compose up -d --no-deps
